# Generated by Django 4.2 on 2023-11-02 15:09

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'purchase'), (2, 'charge')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.UUIDField(default=uuid.uuid4, verbose_name='Invoice number')),
                ('basket', models.ForeignKey(on_delete=models.SET('deleted basket'), related_name='transactions', to='basket.basket', verbose_name='Basket')),
                ('user', models.ForeignKey(on_delete=models.SET('deleted_user'), related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
