# Generated by Django 4.2 on 2023-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=models.SET('deleted basket'), related_name='transactions', to='basket.basket', verbose_name='Basket'),
        ),
    ]
