# Generated by Django 4.2 on 2023-11-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='total',
        ),
    ]
