# Generated by Django 4.2 on 2023-11-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_amount_wallet_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'paid'), (0, 'pending'), (-10, 'Not paid')], default=0),
        ),
    ]
