# Generated by Django 4.2 on 2023-10-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(default='null', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='owner_national_code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='working_perm_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
