# Generated by Django 4.2 on 2023-10-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_provider_name_alter_provider_owner_national_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
