# Generated by Django 4.2 on 2023-10-29 07:33

from django.db import migrations, models
import utils.rate_validator


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[utils.rate_validator.validate_rate]),
        ),
    ]
