# Generated by Django 4.2 on 2023-10-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='User',
            new_name='user',
        ),
    ]
