# Generated by Django 4.2 on 2023-10-29 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Pid'),
        ),
    ]
